openapi: 3.0.3
info:
  contact:
    email: cwe@mitre.org
    name: CWE-CAPEC team
    url: https://github.com/CWE-CAPEC/REST-API-wg
  description: |
    The CWE-CAPEC API specification defines the RESTful semantics for querying the
    CWE and CAPEC data sets from MITRE hosted servers. The goals of this
    API are to provide access to the RAW CWE dataset in JSON form, and to
    perform common search, and filter queries
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: TODO
  title: CWE-CAPEC API 0.1
  version: "0.1"
servers:
- url: /
paths:
  /v1/:
    get:
      operationId: getSupportedInfo
      responses:
        "200":
          description: Server API endpoint and version enumeration
        "404":
          description: No server information available
      summary: |
        Reports supported CWE content and schema versions, with
        their associated response schema version. Includes release
        dates and a list of API endpoints
  /v1/cwe/all/:
    get:
      description: |
        This API endpoint returns all CWE weakness objects
      operationId: getAllCWE
      responses:
        "200":
          description: success
        "204":
          description: good search, but no elements found
        "404":
          description: CWEs at current version not found
        "429":
          description: Too many requests within given time
        "500":
          description: Internal server error
      summary: Get all CWE Weaknesses
  /v1/capec/all/:
    get:
      description: |
        This API endpoint returns all CAPECs
      operationId: getAllCAPEC
      responses:
        "200":
          description: success
        "204":
          description: good search, but no elements found
        "404":
          description: CAPECs at current version not found
        "429":
          description: Too many requests within given time window
        "500":
          description: Internal server error
      summary: Get all CAPECs
  /v1/cwew/:
    get:
      description: |
        This API endpoint returns a given set of CWE weaknesses by identifier
      operationId: getCWEW
      parameters:
      - description: CWE ID to get
        explode: true
        in: query
        name: id
        required: true
        schema:
          items:
            type: string
          type: array
        style: form
      - description: set to any non null value to get plaintextified strings where
          there is HTML in the raw data set
        explode: true
        in: query
        name: plaintext
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: success
        "404":
          description: CWE ID not found
        "500":
          description: Internal server error
      summary: "Get one, or some CWE weaknesses"
  /v1/cwev/:
    get:
      description: |
        This API endpoint returns a given set of CWE views by identifier
      operationId: getCWEV
      parameters:
      - description: CWE ID to get
        explode: true
        in: query
        name: id
        required: true
        schema:
          items:
            type: string
          type: array
        style: form
      - description: set to any non null value to get plaintextified strings where
          there is HTML in the raw data set
        explode: true
        in: query
        name: plaintext
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: success
        "404":
          description: CWE ID not found
        "500":
          description: Internal server error
      summary: "Get one, or some CWE views"
  /v1/cwec/:
    get:
      description: |
        This API endpoint returns a given set of CWE categories by identifier
      operationId: getCWEC
      parameters:
      - description: CWE ID to get
        explode: true
        in: query
        name: id
        required: true
        schema:
          items:
            type: string
          type: array
        style: form
      - description: set to any non null value to get plaintextified strings where
          there is HTML in the raw data set
        explode: true
        in: query
        name: plaintext
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: success
        "404":
          description: CWE ID not found
        "500":
          description: Internal server error
      summary: "Get one, or some CWE categories"
  /v1/capec/:
    get:
      description: |
        This API endpoint returns a given set of CAPECs by identifier
      operationId: getCAPEC
      parameters:
      - description: CAPEC ID to get
        explode: true
        in: query
        name: id
        required: true
        schema:
          items:
            type: string
          type: array
        style: form
      - description: set to any non null value to get plaintextified strings where
          there is HTML in the raw data set
        explode: true
        in: query
        name: plaintext
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: success
        "404":
          description: CAPEC ID not found
        "500":
          description: Internal server error
      summary: "Get one, or some CAPECs"
  /v1/cwe/descendants/:
    get:
      operationId: getDescendants
      parameters:
      - description: View variable is the View_ID field to follow in the Has_Member
          entries and ChildOf relationships
        explode: true
        in: query
        name: view
        required: true
        schema:
          type: string
        style: form
      - description: The id refers to the cwe to grab the children/members/descendants
        explode: true
        in: query
        name: id
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          description: success
      summary: "Get all descendants of a specified weakness, sampling by the view"
  /v1/cwe/parent/:
    get:
      operationId: getParent
      parameters:
      - description: View variable is the View_ID field to follow in the Has_Member
          entries and ChildOf relationships to determine the appropriate
          parent. If there is none the reponse will be empty
        explode: true
        in: query
        name: view
        required: true
        schema:
          type: string
        style: form
      - description: The id refers to the cwe to grab the parent of
        explode: true
        in: query
        name: id
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          description: success
        "404":
          description: CWE ID not found
        "500":
          description: Internal server error
      summary: "Get the parent of a specified weakness, sampling by the view"
  /v1/cwe/enum/:
    get:
      operationId: getCWESchemaEnum
      parameters:
      - description: "the first level element to query about valid response values\
          \ for, if not specified return the entire schema"
        explode: true
        in: query
        name: element
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: The subset of the schema object that is just the requested
            element
        "404":
          description: element not found
        "500":
          description: Internal server error
      summary: Get enumeration of all possible values for a specific field in CWE
  /v1/cwe/meta/:
    get:
      operationId: getCWEMetadata
      parameters:
      - description: CWE version to get meta data for
        explode: true
        in: query
        name: version
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          description: The subset of the schema object that is just the requested
            element
        "404":
          description: Version not found
        "500":
          description: Internal server error
      summary: Get meta data for CWE version including release data
  /v1/capec/enum/:
    get:
      operationId: getCAPECSchemaEnum
      parameters:
      - description: "the first level element to query about valid response values\
          \ for, if not specified return the entire schema"
        explode: true
        in: query
        name: element
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: The subset of the schema object that is just the requested
            element
        "404":
          description: element not found
        "500":
          description: Internal server error
      summary: Get enumeration of all possible values for a specific field in CAPEC
  /v1/capec/meta/:
    get:
      operationId: getCAPECMetadata
      parameters:
      - description: CAPEC version to get meta data for
        explode: true
        in: query
        name: version
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          description: The subset of the schema object that is just the requested
            element
        "404":
          description: Version not found
        "500":
          description: Internal server error
      summary: Get meta data for CAPEC version including release data
components:
  schemas: {}
