# Forked from https://github.com/ThreatDataScience/taxii2-openapi/blob/master/swagger.yaml
openapi: '3.0.3'
info:
  version: "0.1"
  title: "CWE-CAPEC API 0.1"
  description: |
    The CWE-CAPEC API specification defines the RESTful semantics for querying
    the CWE and CAPEC data sets from MITRE hosted servers. The goals of this
    API are to provide access to the RAW CWE dataset in JSON form, and to
    perform common search, and filter queries
  termsOfService: "TODO"
  contact:
    name: "CWE-CAPEC team"
    url: "https://github.com/CWE-CAPEC/REST-API-wg"
    email: 
      - "cwe@mitre.org"
      - "capec@mitre.org"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
tags: 
  # TODO

paths:
  /v1/:
    get:
      summary: |
        Reports supported CWE content and schema versions, with
        their associated response schema version. Includes release
        dates and a list of API endpoints
      operationId: getSupportedInfo
      responses:
        200:
          description: Server API endpoint and version enumeration
          schema:
            $ref: # TODO
        404:
          description: No server information available
        429:
          description: Too many requests within given time
  /v1/cwe/all/:
    get:
      summary: Get all CWEs
      operationId: getAllCWE
      description: |
        This API endpoint returns all CWE weakness objects
      parameters:
        - in: query
          name: version
          description: CWE version to query into - defaults to current
          required: false 
          type: string
        - in: query
          name: plaintext
          description: set to any non null value to get plaintextified strings
            where there is HTML in the raw data set
          required: false 
          schema:
            type: string
          default: false
        - in: query
          name: filter 
          description: Top level elements to include in response
          required: false
          schema:
            type: array
            items:
              type: string
        - in: query
          name: search
          description: Generic search for fields matching or containing particular values
          required: false
          schema:
            type: object
      responses:
        200:
          description: 
          schema:
            type: array
            items:
              oneOf:
                - $ref: 'https://raw.githubusercontent.com/CWE-CAPEC/REST-API-wg/main/specifications/weakness.json'
                - $ref: 'https://raw.githubusercontent.com/CWE-CAPEC/REST-API-wg/main/specifications/view_schema.json'
                - $ref: 'https://raw.githubusercontent.com/CWE-CAPEC/REST-API-wg/main/specifications/category_schema.json'
        404:
          description: CWEs at current version not able to be found
        429:
          description: Too many requests within given time
  /v1/capec/all/:
    get:
      summary: Get all CAPECs
      operationId: getAllCAPEC
      description: |
        This API endpoint returns all CAPECs
      parameters:
        - in: query
          name: version
          description: CWE version to get meta data for
          required: true
          type: string
      responses:
        200:
          description: 
          schema:
            $ref: #TODO CAPEC Response schema
        404:
          description: CAPECs at current version not found
        429:
          description: Too many requests within given time window
  /v1/cwe/:
    get:
      summary: Get one, or some CWEs
      operationId: getCWE
      parameters: 
        - in: query
          name: id
          description: CWE ID to get
          required: true
          schema:
            type: array
            items:
              type: string
        - in: query
          name: version
          description: CWE version to query into - defaults to current
          required: false 
          type: string
        - in: query
          name: plaintext
          description: set to any non null value to get plaintextified strings
            where there is HTML in the raw data set
          required: false 
          schema:
            type: string
          default: false
        - in: query
          name: filter 
          description: Top level elements to include in response
          required: false
          schema:
            type: array
            items:
              type: string
        - in: query
          name: search
          description: Generic search for fields matching or containing particular values
          required: false
          schema:
            type: object

      description: |
        This API endpoint returns a given set of CWEs which may be filtered
        down by a list of id's, and may have their response JSON content
        filtered by key
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              oneOf:
                - $ref: 'https://raw.githubusercontent.com/CWE-CAPEC/REST-API-wg/main/specifications/weakness.json'
                - $ref: 'https://raw.githubusercontent.com/CWE-CAPEC/REST-API-wg/main/specifications/view_schema.json'
                - $ref: 'https://raw.githubusercontent.com/CWE-CAPEC/REST-API-wg/main/specifications/category_schema.json'
        404:
          description: CWE IDs not found, or other query error.
            Search&filter queries which are correctly formed but imply an empty
            response will not error.
        429:
          description: Too many requests within given time
  /v1/CAPEC/:
    get:
      summary: Get one, or some CAPECs
      operationId: getCAPEC
      parameters: 
        - in: query
          name: id
          description: CAPEC ID to get
          required: true
          schema:
            type: array
            items:
              type: string
        - in: query
          name: plaintext
          description: set to any non null value to get plaintextified strings
            where there is HTML in the raw data set
          required: false 
          schema:
            type: string
        # - in: query
        #   name: search
        #   description: Generic search
        #   required: false
        #   schema:
        #     type: object
        # - in: query
        #   name: filter 
        #   description: Top level elements to include in response
        #   required: false
        #   schema:
        #     type: array

      description: |
        This API endpoint returns a given set of CAPECs by identifier
      responses:
        200:
          description: success
          schema:
            $ref: #TODO CWE Response schema
        404:
          description: CAPEC ID not found
        429:
          description: Too many requests within given time
  /v1/cwe/descendants/:
    get:
      summary: Get all descendants of a specified weakness, sampling by the view
      description: Request children of a particular object ID, including
        categories and views.
      operationId: getCWEDescendants
      parameters: 
        - in: query
          name: version
          description: CWE version to query into - defaults to current
          required: false 
          type: string
        - in: query
          name: view
          description: View variable is the View_ID field to follow in the
            Has_Member entries and ChildOf relationships. The variable is
            required, because walking the CWE data set by Relationship without
            a View_ID results in a non-tree structure
          required: true
          schema:
            type: string
        - in: query
          name: id
          description: The id refers to the cwe to grab the children/members/descendants  
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              oneOf:
                - $ref: 'https://raw.githubusercontent.com/CWE-CAPEC/REST-API-wg/main/specifications/weakness.json'
                - $ref: 'https://raw.githubusercontent.com/CWE-CAPEC/REST-API-wg/main/specifications/view_schema.json'
                - $ref: 'https://raw.githubusercontent.com/CWE-CAPEC/REST-API-wg/main/specifications/category_schema.json'
        404:
          description: Error unable to find decendenants for ID
  /v1/cwe/enum/:
    get:
      summary: Get enumeration of all possible values for a specific field in CWE
      operationId: getCWESchemaEnum
      parameters:
        - in: query
          name: element
          description: the first level element to query about valid response
            values for, if not specified return the entire schema
          required: false
          type: string
      responses:
        200:
          description: The subset of the schema object that is just the requested element
          schema:
            $ref: https://json-schema.org/draft/2020-12/output/schema
        404:
          description: element not found
        429:
          description: Too many requests within given time
  /v1/cwe/meta/:
    get:
      summary: Get meta data for CWE version including release data
      operationId: getCWEMetadata
      parameters:
        - in: query
          name: version
          description: CWE version to get meta data for
          required: true
          type: string
      responses:
        200:
          description: The subset of the schema object that is just the requested element
          schema:
            type: object
            properties:
              releaseDate: string
              version: string
              schemaVersion: string
        404:
          description: Version not found
        429:
          description: Too many requests within given time
  /v1/cwe/changes/:
    get:
      summary: Get list of changes between two dates or versions
      operationId: getCWEChanges
      parameters:
        - in: query
          name: element
          description: the first level element to query about valid response
            values for, if not specified return the entire schema
          required: false
          type: string
      responses:
        200:
          description: The subset of the schema object that is just the requested element
          schema:
            $ref: #TODO Decide 09082022
        404:
          description: element not found
        429:
          description: Too many requests within given time
  /v1/capec/enum/:
    get:
      summary: Get enumeration of all possible values for a specific field in CAPEC
      operationId: getCAPECSchemaEnum
      parameters:
        - in: query
          name: element
          description: the first level element to query about valid response
            values for, if not specified return the entire schema
          required: false
          type: string
      responses:
        200:
          description: The subset of the schema object that is just the requested element
          schema:
            $ref: https://json-schema.org/draft/2020-12/output/schema
        404:
          description: element not found
  /v1/capec/meta/:
    get:
      summary: Get meta data for CAPEC version including release data
      operationId: getCAPECMetadata
      parameters:
        - in: query
          name: version
          description: CAPEC version to get meta data for
          required: true
          type: string
      responses:
        200:
          description: The subset of the schema object that is just the requested element
          schema:
            $ref: #TODO
        404:
          description: Version not found



